# Generated by Django 5.2.3 on 2025-07-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discount_price_product_photo_product_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
