# Generated by Django 5.2.3 on 2025-06-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
