# Generated by Django 5.2.3 on 2025-06-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_groups_users_is_superuser_users_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
