# Generated by Django 5.2.3 on 2025-06-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
