# Generated by Django 5.2.3 on 2025-06-26 04:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_admin_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
