# Generated by Django 5.2.3 on 2025-06-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='./media/profile_pictures/Screenshot_from_2025-06-16_14-04-29.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
